### ISSUE TITLE
org-capture placeholders broken in current (28.0.50) known good build

### ISSUE THREAD

**Issue by ksafford** [jimeh/emacs-builds#16]
This resolved [issue](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49746) seems to be included in the as-of-today know good build: [Emacs.2021-10-24.608e694.master](https://github.com/jimeh/emacs-builds/releases/tag/Emacs.2021-10-24.608e694.master).

The issue prevents certain capture templates from working. For example those that prompt for a tag.

**Comment by jimeh** [comment]
Apologies for that, I don't really use org-capture myself, hence I missed it. And my testing for known-good is basically using it personally for a day or two without issues.

I've just updated the known good build to the 2021-11-10 nightly. I'd been holding off on it as I've been having a weird UI glitch on and off, but I suspect it's actually a package issue, nor is does it actually break anything.

The very long gap between the July and October and known good builds were due to non-native fullscreen issues I ran into in the summer after a bunch of the macOS window handling code was refactored, but that's mostly been resolved now.

Feel free to re-open this issue, or open a new one if you still have issues with the new known-good build.

**Comment by ksafford** [comment]
Thanks! Nothing to apologize for. This tap is super helpful. I was having some struggles with compiling emacs28 before discovering your repo here.

**Comment by jimeh** [comment]
If you're feeling adventurous you could always use the [build script](https://github.com/jimeh/build-emacs-for-macos) yourself locally. It's mostly pain-free :)

Though, the whole reason I setup this repo and the homebrew tap was cause I personally got tired of spending around 25 minutes every couple of days making a new build locally with my laptop fans sounding like a jet engine :)

**Comment by ksafford** [comment]
I may give it a try next time. Just tested the org-capture templates and it's working now. Really appreciate the fast response. Great project.
