### ISSUE TITLE
mu4e is missing in the builded app

### ISSUE THREAD

**Issue by maikol-solis** [jimeh/emacs-builds#19]
I installed your latest nightly from the emacs-28 and I got this error at startup 

```
Warning (initialization): An error occurred while loading ‘/Users/maikol/.emacs.d/init.el’:

Error in private config: config.el, (file-missing Cannot open load file No such file or directory mu4e)

```

The temporary solution is to add this to the config 
```
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu/mu4e")
```

I think that loading mu4e should be loading directly by the app instead of the user. 

Best.

**Comment by jimeh** [comment]
Apologies, this issue came up in the [comments](https://www.reddit.com/r/emacs/comments/r9lkmi/comment/hnkvjqg) on Reddit a few months back, and I managed to completely forget about it.

I've now raised a [pull request](https://github.com/jimeh/build-emacs-for-macos/pull/66) with what should hopefully fix it, and I've fired off a [test build](https://github.com/jimeh/emacs-builds/actions/runs/1809690151) from that PR to verify it works.

If the build succeeds and you're feeling adventurous, feel free to download the `dmg` artifact to test it. I'll be testing it myself sometime tomorrow.

**Comment by jimeh** [comment]
That's now merged, so starting with next nightly builds (2022-02-08, in about 23 hours), mu4e and other emacs packages made available via a homebrew formula should work out of the box.

**Comment by maikol-solis** [comment]
Thanks for your help!

**Comment by chuxubank** [comment]
Hi @jimeh Could we also add `/opt/homebrew/share/emacs/site-lisp/` to load-path?
I find it worked to add something like `export EMACSLOADPATH="/opt/homebrew/share/emacs/site-lisp/:"`
but it is hard to make it work for GUI Emacs.

**Comment by jimeh** [comment]
@chuxubank Good point, I forgot about that when I finally got Apple Silicon support fully working last year.

**Comment by jimeh** [comment]
@chuxubank this has been added in [v0.6.48](https://github.com/jimeh/build-emacs-for-macos/releases/tag/v0.6.48) of the build script, and build workflows here have been updated to use that new version.

I've tested it with mu4e, and it can load it correctly on an Apple Silicon machine.

**Comment by chuxubank** [comment]
@jimeh Thanks for your great work!
