### ISSUE TITLE
Bump stable to 29.3

### ISSUE THREAD

**Issue by dpassen** [jimeh/emacs-builds#27]
https://lists.gnu.org/archive/html/emacs-devel/2024-03/msg00611.html

**Comment by maikol-solis** [comment]
Perhaps the motivation to upgrade as soon as possible is this part. 

> Emacs 29.3 is an emergency bugfix release; it includes no new features except a small number of changes intended to resolve security vulnerabilities uncovered in Emacs 29.2.

The relevant discussion about the bug fix is here https://seclists.org/oss-sec/2024/q1/250

**Comment by jimeh** [comment]
Thanks for the poke, and apologies for lagging behind with this. I'll try and get a new stable build out in the next few days.

Annoyingly, right now I can't just click a button to do a stable build as I usually would. All builds currently fail due to Apple changing how their notarization process works about a week ago, and I haven't had time to look at it yet. But this has bumped it up to the top of my priority list.

**Comment by jimeh** [comment]
29.3 is now released: https://github.com/jimeh/emacs-builds/releases/tag/Emacs-29.3
